### ISSUE TITLE
Can not select language

### ISSUE THREAD

**Issue by trezum** [e-gautier/githunt#10]
i can not select what language to display on the page, the time periode drop down works prefectly but the language selection does not affect the result. 
It is the same thing in firefox and chrome. 
Any advice?

**Comment by e-gautier** [comment]
Hello, It's a free text input, you can put whatever you want. Then hit enter to reload the result.

**Comment by e-gautier** [comment]
Closing

**Comment by trezum** [comment]
My mistake, i was typing c# instead of CSharp
